pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/muthu512/test1.git'  // Clone repo
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'  // Build project and generate the JAR
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'  // Run tests
            }
        }
        stage('Deploy') {
            steps {
                sh 'java -jar target/online-1-0.0.1-SNAPSHOT.jar'  // Run the JAR generated by Maven
            }
        }
    }
}


